# Generated by Django 5.0.3 on 2025-02-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='employee/')),
                ('degree', models.CharField(max_length=255)),
            ],
        ),
    ]
