# Generated by Django 5.0.3 on 2025-02-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_app', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='order',
            field=models.BooleanField(default=False),
        ),
    ]
