# Generated by Django 5.0.3 on 2025-02-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_app', '0003_employee_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
