# Generated by Django 5.0.3 on 2025-02-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_proba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proba',
        ),
    ]
