# Generated by Django 5.0.3 on 2025-02-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_delete_proba'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodfilter',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
