# Generated by Django 5.0.3 on 2025-04-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_periodfilter_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
